- index.js
Tested using react-native 0.14.2
> Fix "requiring unknown module" error

- index.js
- src/main/java/com/burnweb/rnsendintent/RNSendIntentModule.java
Thanks for this library!
Sending this pull in case it helps others – I initially thought `sendText` would actually trigger SMS messages like this.
> Support for sending SMS messages

- README.md
- index.js
This will solve the `undefined is not a function` for addCalendarEvent
https://github.com/lucasferreira/react-native-send-intent/issues/11
> Fix naming consistency

- src/main/java/com/burnweb/rnsendintent/RNSendIntentModule.java
Changed SimpleDateFormat which had led to an unparsable date exception
> Unparsable date exception

- README.md
- index.js
- src/main/java/com/burnweb/rnsendintent/RNSendIntentModule.java
A small addition, allowing for automatic addition of location when saving events to the calendar
> Added support for automatically adding locations for events

- index.js
Update the imports for React Native 0.26
> Update imports for React Native 0.26

- android/src/main/java/com/burnweb/rnsendintent/RNSendIntentModule.java
- index.js
Allow to send email for selected address
> Add send e-mail intent

- README.md
- android/src/main/java/com/burnweb/rnsendintent/RNSendIntentModule.java
- index.js
Added in the intent to open up the
> Added Intent for opening the chooser dialog

- android/src/main/java/com/burnweb/rnsendintent/RNSendIntentModule.java
- index.js
Additional boolean argument to allow having an All Day event added to the calendar
> Added boolean flag for all day event

- README.md
- android/src/main/java/com/burnweb/rnsendintent/RNSendIntentModule.java
- index.js
Hi Lucas,
Thanks for releasing react-native-send-intent. I've added a couple functions that I consider fit into this app and make it more useful.
Let me know what you think
Thanks, cheers
Miguel
> Added openApp and isAppInstalled methods

- README.md
- android/build.gradle
- android/src/main/java/com/burnweb/rnsendintent/RNSendIntentModule.java
- index.js
- package.json
This allows for the passing of arbitrary data to opened applications. It expects that `extras` be a map of string->string.
> Open app extras

- README.md
- android/src/main/java/com/burnweb/rnsendintent/RNSendIntentModule.java
- index.js
Hi Lucas,
Thank you very much for react-native-send-intent. I have added two feature for share image to instagram and share text to line.
example:
SendIntentAndroid.shareImageToInstagram("image/*", "You Image File URI");
SendIntentAndroid.shareTextToLine({text: "Your Text Content"});
> - added shareTextToLine and shareTextToLine method

- android/src/main/java/com/burnweb/rnsendintent/RNSendIntentModule.java
Propose change to allow for ussd calls to be made.
> Allow USSD calls

- README.md
- android/src/main/java/com/burnweb/rnsendintent/RNSendIntentModule.java
- index.js
Adds a function to create an intent with ACTION_VIEW, a package, a data uri and optional extras.
I also added a more sophisticated method to add the extras object. The way it was before only allowed strings and failed with anything else. Handling all the primitives was tricky, since JS only supports Number, so I kind of misused an object with a type and value key.
Also, I only tested the int variant, so I'm not sure that all the casts work as intended.
> Add openAppWithData

- index.js
not exception when not link.
when you have an hot update ,like code-push . import the module and not exception is very import.
> not exception when not link

- README.md
- android/src/main/java/com/burnweb/rnsendintent/RNSendIntentModule.java
- index.js
There is an issue about it somewhere in the repo. So I created it. :) Am option to enable only phone app usage when calling.
> Option to use phone app only on Android

- android/src/main/AndroidManifest.xml
- android/src/main/java/com/burnweb/rnsendintent/FileProvider.java
fixed https://github.com/lucasferreira/react-native-send-intent/issues/83
> Solve the conflict between FileProvider and other libraries

- README.md
- android/src/main/java/com/burnweb/rnsendintent/RNSendIntentModule.java
- index.js
- will open default mail client. 
Similar to #76, but not using the fallback.
> Add openEmailApp intent

- README.md
- android/src/main/java/com/burnweb/rnsendintent/RNSendIntentModule.java
- index.js
> Implement DownloadManager.ACTION_VIEW_DOWNLOADS intent

- android/src/main/java/com/burnweb/rnsendintent/RNSendIntentModule.java
- index.d.ts
- index.js
Implements #97.
Please let me know if you want to make any change!
> Add gotoHomeScreen to allow to return to home screen

- README.md
- android/src/main/java/com/burnweb/rnsendintent/RNSendIntentModule.java
- index.d.ts
- index.js
1. Add new function to show a selector of all email apps that are available in that device
2. Update all other files that are related
3. update readme file
> Open all Email apps that are available.

- android/src/main/java/com/burnweb/rnsendintent/RNSendIntentModule.java
- index.js
Hello.
I am using a function that starts an Intent with only URI, and I hope the above functions are merged into the project.
> add open Intent With URi
